export const sectionPages = {
  outwardGatePass: {
    sectionKey: "section-5",
    pageKey: "outward-gate-pass-records",
    title: "Outward Gate Pass Records",
    sheetTitle: "RETURNABLE OUTWARD GATE PASS RECORD",
    groupTitle: "ITEM DETAILS  |  OUTWARD RECORD  |  INWARD RECORD",
    theme: "gatepass",
    columns: [
      { key: "S/N", label: "S/N", width: 70 },
      { key: "Description", label: "Description", width: 260 },
      { key: "UOM", label: "UOM", width: 85 },
      { key: "Qty", label: "Qty", type: "number", width: 80 },
      { key: "Purpose", label: "Purpose", width: 210 },
      { key: "Supplier / Vendor", label: "Supplier / Vendor", width: 190 },
      { key: "ROGP NO#", label: "ROGP NO#", width: 110 },
      { key: "Out Date", label: "Out Date", type: "date", width: 130 },
      { key: "Taken By", label: "Taken By", width: 140 },
      { key: "ROIGP NO#", label: "ROIGP NO#", width: 110 },
      { key: "IN Date", label: "IN Date", type: "date", width: 130 },
      { key: "Brought By", label: "Brought By", width: 140 },
      { key: "STATUS", label: "STATUS", width: 120 },
      { key: "Remarks", label: "Remarks", width: 170 },
    ],
  },

  iutnOutward: {
    sectionKey: "section-5",
    pageKey: "iutn-outward-record",
    title: "IUTN Outward Record",
    sheetTitle: "RETURNABLE OUTWARD GATE PASS RECORD",
    groupTitle: "ITEM DETAILS  |  INWARD RECORD  |  OUTWARD RECORD",
    theme: "gatepass",
    columns: [
      { key: "S/N", label: "S/N", width: 70 },
      { key: "Description", label: "Description", width: 260 },
      { key: "UOM", label: "UOM", width: 85 },
      { key: "Qty", label: "Qty", type: "number", width: 80 },
      { key: "Purpose", label: "Purpose", width: 210 },
      { key: "Supplier / Vendor", label: "Supplier / Vendor", width: 190 },
      { key: "IUTN NO#", label: "IUTN NO#", width: 110 },
      { key: "IN Date", label: "IN Date", type: "date", width: 130 },
      { key: "Brought By", label: "Brought By", width: 140 },
      { key: "IUTN NO# 2", label: "IUTN NO#", width: 110 },
      { key: "Out Date", label: "Out Date", type: "date", width: 130 },
      { key: "Taken By", label: "Taken By", width: 140 },
      { key: "STATUS", label: "STATUS", width: 120 },
      { key: "Remarks", label: "Remarks", width: 170 },
    ],
  },

  fuelDashboard: {
    sectionKey: "section-6",
    pageKey: "executive-dashboard",
    title: "Petrol Consumption Dashboard",
    sheetTitle: "PETROL CONSUMPTION DASHBOARD",
    groupTitle: "Employee Name: Zeeshan Aslam  |  Report Framework: May 2026 - Dec 2026",
    sourceFile: "Fuel_Consumption_Log.xlsx",
    theme: "fuel",
    columns: [
      { key: "Month Period", label: "Month Period", width: 160 },
      { key: "No. of Trips", label: "No. of Trips", type: "number", width: 130 },
      { key: "Total Distance (KM)", label: "Total Distance (KM)", type: "number", width: 180 },
      { key: "Total Fuel (Ltrs)", label: "Total Fuel (Ltrs)", type: "number", width: 170 },
      { key: "Total Price (Rs.)", label: "Total Price (Rs.)", type: "number", width: 170 },
    ],
  },

  monthlyTravel: {
    sectionKey: "section-6",
    pageKey: "monthly-travel-entries",
    title: "Monthly Travel Entries",
    sheetTitle: "ENGINEERING - TRAVEL & FUEL CONSUMPTION RECORDS",
    groupTitle: "Travel & Fuel Consumption Records",
    theme: "fuel",
    columns: [
      { key: "Date", label: "Date", type: "date", width: 150 },
      { key: "Month", label: "Month", width: 140, readOnly: true },
      {
        key: "Purpose / Justification of Visit",
        label: "Purpose / Justification of Visit",
        width: 390,
      },
      { key: "From Location", label: "From Location", width: 130 },
      { key: "To Market / Vendor", label: "To Market / Vendor", width: 240 },
      { key: "No. of Trips", label: "No. of Trips", type: "number", width: 115 },
      { key: "Going Dist.(KM)", label: "Going Dist.(KM)", type: "number", width: 135 },
      { key: "Return Dist.(KM)", label: "Return Dist.(KM)", type: "number", width: 145 },
      {
        key: "Total Dist.(KM)",
        label: "Total Dist.(KM)",
        type: "number",
        width: 140,
        readOnly: true,
      },
      { key: "Fuel Paid (Rs.)", label: "Fuel Paid (Rs.)", type: "number", width: 140 },
      {
        key: "Fuel Rate (Rs./Ltr)",
        label: "Fuel Rate (Rs./Ltr)",
        type: "number",
        width: 150,
      },
      {
        key: "Petrol (Liters)",
        label: "Petrol (Liters)",
        type: "number",
        width: 140,
        readOnly: true,
      },
    ],
  },

  toolsIssuance: {
    sectionKey: "section-7",
    pageKey: "tools-issuance",
    title: "Tools Issuance",
    sheetTitle: "NAME WISE TOOLS ISSUED — FULL DETAIL LIST",
    groupTitle: "Tools Issuance Register",
    theme: "tools",
    columns: [
      { key: "SR #", label: "SR #", width: 85 },
      { key: "ISSUE DATE", label: "ISSUE DATE", type: "date", width: 150 },
      { key: "TOOL / ITEM NAME", label: "TOOL / ITEM NAME", width: 320 },
      { key: "DEPARTMENT", label: "DEPARTMENT", width: 190 },
      { key: "QTY ISSUED", label: "QTY ISSUED", type: "number", width: 120 },
      { key: "REPLACEMENT", label: "REPLACEMENT", width: 220 },
      { key: "REMARKS / CONDITION", label: "REMARKS / CONDITION", width: 340 },
      { key: "Issued To", label: "Issued To", width: 190 },
    ],
  },
};
